### ISSUE TITLE
AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by shaunhurryup** [bityigoss/mtl-text-recognition#13]
错误如下：
--------------------------------------------------------------------------------
dataset_root: data/data10879/train_images
opt.select_data: ['/']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    data/data10879/train_images	 dataset: /
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    train(opt)
  File "train.py", line 30, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/aistudio/mtl-text-recognition/utils/dataset.py", line 37, in __init__
    _dataset = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/home/aistudio/mtl-text-recognition/utils/dataset.py", line 106, in hierarchical_dataset
    concatenated_dataset = ConcatDataset(dataset_list)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 188, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'
AssertionError: datasets should not be an empty iterable

非常期待你的回答，感谢！

**Comment by bityigoss** [comment]
看起来应该是没有读到数据吧
