### ISSUE TITLE
运行mtl_train.py出错

### ISSUE THREAD

**Issue by luvwinnie** [bityigoss/mtl-text-recognition#17]
我运行你的代码使用自己的SyntheticChineseText，出现以下的cost.backward的Runtime错误。请问你有出现过这个错误吗？

```
Traceback (most recent call last):
  File "mtl_train.py", line 351, in <module>
    train(opt)
  File "mtl_train.py", line 196, in train
    cost.backward()
  File "/venv/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: The size of tensor a (0) must match the size of tensor b (5990) at non-singleton dimension 2
```

**Comment by SuitsHe** [comment]
老哥我也出现一样的报错，请问你是怎么解决的呢？
